### ISSUE TITLE
dh-virtualenv trigger the systemwide setup of the python package during the package build with debuild

### ISSUE THREAD

**Issue by evilaliv3** [spotify/dh-virtualenv#126]
hello there!

we are testing dh-virtualenv within the [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks) project in order to solve https://github.com/globaleaks/GlobaLeaks/issues/1555

it seems (but i maybe wrong in this) that running "debuild" having configured the debian/rules as by [1] that dh-virtualenv is trying to install the package systemwide on the local system where i try to build the package.

this is happening on an ubuntu14.04 using the ubuntu package dh-virtualenv 0.6.

the following is the error i get given the fact that i build with my user and my user is not allowed to write in /usr/share on the machine i use to build packages:
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating /usr/share/globaleaks
error: could not create '/usr/share/globaleaks': Permission denied

```
Traceback (most recent call last):
  File "/usr/bin/dh_virtualenv", line 102, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/dh_virtualenv", line 97, in main
    deploy.install_package()
  File "/usr/lib/python2.7/dist-packages/dh_virtualenv.py", line 123, in install_package
    os.path.join(self.package_dir, 'include/site/python2.6'),
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['debian/globaleaks/usr/share/python/globaleaks/bin/python', 'setup.py', 'install', '--record', '/tmp/tmpoQ1Wqq', '--install-headers', 'debian/globaleaks/usr/share/python/globaleaks/include/site/python2.6']' returned non-zero exit status 1
make: *** [binary] Error 1
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc failed
```

[1] https://github.com/spotify/dh-virtualenv/blob/master/README.md#using-dh-virtualenv

**Comment by evilaliv3** [comment]
ok managed to solve the issue by my own.

the issue was not related to dh-virtualenv but to my faul in using absolute path in setuptools data_files argument.

:) thank you anyway.
