### ISSUE TITLE
Python3 build fails: ensurepip module not found

### ISSUE THREAD

**Issue by rkubik** [spotify/dh-virtualenv#130]
Building packages on Debian 8, I come across an issue with pyvenv looking for the ensurepip module. Curious how you mitigated this issue?

```make
override_dh_virtualenv:
	dh_virtualenv --builtin-venv --python /usr/bin/python3.4 -v
```

```python
I: dh_virtualenv:70: myproject: Processing package...
I: dh_virtualenv:70: myproject: Adding autoscripts...
I: dh_virtualenv:70: myproject: Creating virtualenv
Error: Command '['/srv/misc/skele/src/python3/virtualenv/debian/myproject/usr/share/python/myproject/bin/python3.4', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/bin/dh_virtualenv", line 106, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/dh_virtualenv", line 83, in main
    deploy.create_virtualenv()
  File "/usr/lib/python2.7/dist-packages/dh_virtualenv/deployment.py", line 112, in create_virtualenv
    subprocess.check_call(virtualenv)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.4', '-m', 'venv', 'debian/myproject/usr/share/python/myproject']' returned non-zero exit status 1
```

Ref: https://bugs.launchpad.net/debian/+source/python3.4/+bug/1290847

**Comment by rkubik** [comment]
This issue is distro-dependent, my version from Jessie does not include ensurepip and requires a patch.
