### ISSUE TITLE
fix_shebangs doesn't work for paths containing hyphens

### ISSUE THREAD

**Issue by mjksmith** [spotify/dh-virtualenv#139]
PR #136 uses a '-' as a delimiter for the sed replace command, which causes errors when fix_shebangs gets a path that contains a hyphen.

Here's an example of it breaking:

```
16:29:14 running test
16:29:14 sed: -e expression #1, char 79: unknown option to `s'
16:29:14 Traceback (most recent call last):
16:29:14   File "/usr/bin/dh_virtualenv", line 106, in <module>
16:29:14     sys.exit(main() or 0)
16:29:14   File "/usr/bin/dh_virtualenv", line 98, in main
16:29:14     deploy.fix_shebangs()
16:29:14   File "/usr/lib/python2.7/dist-packages/dh_virtualenv/deployment.py", line 177, in fix_shebangs
16:29:14     subprocess.check_call(['sed', '-i', regex, f])
16:29:14   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
16:29:14     raise CalledProcessError(retcode, cmd)
16:29:14 subprocess.CalledProcessError: Command '['sed', '-i', 's-^#!.*bin/\\(env \\)\\?\\(python\\|pypy\\|ipy\\|jython\\)-#!/usr/share/python/paasta-tools/bin/python-', 'debian/paasta-tools/usr/share/python/paasta-tools/bin/easy_install']' returned non-zero exit status 1
```

Link to the sed [here](https://github.com/spotify/dh-virtualenv/pull/136/files#diff-b432c676336e8409fc43c7cfdc7c78e1R175)

**Comment by jhermann** [comment]
A safe(r) char to use is ':' cause it's used in $PATH.
