### ISSUE TITLE
Default --no-test?

### ISSUE THREAD

**Issue by asottile** [spotify/dh-virtualenv#148]
As far as I can tell, very few packages actually use `python setup.py test` to run their tests (since it triggers `easy_install` + eggs and such).  The docs mention the use of setuptools vs distutils which doesn't seem entirely true.

With python3.4, `python setup.py test` on a trivial package is usually a noop:

```
mkdir tests
echo 'import pytest' > tests/__init__.py
echo 'from setuptools import setup; setup(name="demo")' > setup.py
virtualenv venv34 -ppython3.4
./venv34/bin/python setup.py test
```

Output:

```
$ venv34/bin/python setup.py test
running test
running egg_info
writing top-level names to demo.egg-info/top_level.txt
writing demo.egg-info/PKG-INFO
writing dependency_links to demo.egg-info/dependency_links.txt
reading manifest file 'demo.egg-info/SOURCES.txt'
writing manifest file 'demo.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

But under python3.5 this is no longer the case:

```
mkdir tests
echo 'import pytest' > tests/__init__.py
echo 'from setuptools import setup; setup(name="demo")' > setup.py
virtualenv venv35 -ppython3.5
./venv35/bin/python setup.py test
```

Output:

```
$ ./venv35/bin/python setup.py test
running test
running egg_info
writing dependency_links to demo.egg-info/dependency_links.txt
writing demo.egg-info/PKG-INFO
writing top-level names to demo.egg-info/top_level.txt
reading manifest file 'demo.egg-info/SOURCES.txt'
writing manifest file 'demo.egg-info/SOURCES.txt'
running build_ext
tests (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/tmp/foo/tests/__init__.py", line 1, in <module>
    import pytest
ImportError: No module named 'pytest'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

This makes the trivial package fail :(

A hacky workaround that I can use in packages I own and can modify:

```python
from setuptools import setup
from setuptools.command.test import test as _test


class test(_test):
    def run(self):
        print('Run tests through tox / pytest instead')

setup(
    name="demo",
    cmdclass={'test': test},
)
```

Or I can add `--no-test`

But I'd really love to not have to do that :)

**Comment by nailor** [comment]
Yeah, I see lot of people making their packges to run with `--no-test`, so this would probably make sense.

However, need to come up with some nice transition scheme
