### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Nadav-Ruskin** [spotify/dh-virtualenv#232]
Howdy,

First of all, thank you for sharing this promising utility. Unfortunately, I have problems running it.

My system is Ubuntu 18.04 on WSL. I followed the documented tutorial and have the necessary files under `/debian`. I have also dumbed down my `setup.py` to the bare minimum in an attempt to debug the situation. Here is the error I keep receiving:

```
nadav@DESKTOP-4DUIS04:/mnt/c/Git/configsite$ dpkg-buildpackage -us -uc
dpkg-buildpackage: info: source package configsite
dpkg-buildpackage: info: source version 0.1-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Nadav Ruskin <ruskin.nadav@gmail.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build configsite
 fakeroot debian/rules clean
dh clean --with python-virtualenv --python /usr/bin/python3 --builtin-venv
   dh_testdir -O--python=/usr/bin/python3 -O--builtin-venv
   dh_clean -O--python=/usr/bin/python3 -O--builtin-venv
 dpkg-source -b configsite
dpkg-source: warning: no source format specified in debian/source/format, see dpkg-source(1)
dpkg-source: info: using source format '1.0'
dpkg-source: warning: source directory 'configsite' is not <sourcepackage>-<upstreamversion> 'configsite-0.1'
dpkg-source: info: building configsite in configsite_0.1-1.tar.gz
dpkg-source: info: building configsite in configsite_0.1-1.dsc
 debian/rules build
make: 'build' is up to date.
 fakeroot debian/rules binary
dh binary --with python-virtualenv --python /usr/bin/python3 --builtin-venv
   dh_testdir -O--python=/usr/bin/python3 -O--builtin-venv
   dh_update_autotools_config -O--python=/usr/bin/python3 -O--builtin-venv
   dh_auto_configure -O--python=/usr/bin/python3 -O--builtin-venv
   dh_testroot -O--python=/usr/bin/python3 -O--builtin-venv
   dh_prep -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installdirs -O--python=/usr/bin/python3 -O--builtin-venv
   dh_install -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installdocs -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installchangelogs -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installexamples -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installman -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installcatalogs -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installcron -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installdebconf -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installemacsen -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installifupdown -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installinfo -O--python=/usr/bin/python3 -O--builtin-venv
   dh_virtualenv -O--python=/usr/bin/python3 -O--builtin-venv
Requirement already satisfied: setuptools in ./debian/configsite/opt/venvs/configsite/lib/python3.6/site-packages (from -r ./requirements.txt (line 1))
Collecting click==6.7 (from -r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting Flask==1.0.2 (from -r ./requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whlCollecting gunicorn==19.8.1 (from -r ./requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/55/cb/09fe80bddf30be86abfc06ccb1154f97d6c64bb87111de066a5fc9ccb937/gunicorn-19.8.1-py2.py3-none-any.whl
Collecting itsdangerous==0.24 (from -r ./requirements.txt (line 5))
Collecting Jinja2==2.10 (from -r ./requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whlCollecting jsonschema==2.6.0 (from -r ./requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting MarkupSafe==1.0 (from -r ./requirements.txt (line 8))
Collecting Werkzeug==0.14.1 (from -r ./requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl
Installing collected packages: click, MarkupSafe, Jinja2, itsdangerous, Werkzeug, Flask, gunicorn, jsonschema
Successfully installed Flask-1.0.2 Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 click-6.7 gunicorn-19.8.1 itsdangerous-0.24 jsonschema-2.6.0
Processing /mnt/c/Git/configsite
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-1iou1j1o-build/
Traceback (most recent call last):
  File "/usr/bin/dh_virtualenv", line 106, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/dh_virtualenv", line 89, in main
    deploy.install_package()
  File "/usr/lib/python2.7/dist-packages/dh_virtualenv/deployment.py", line 236, in install_package
    subprocess.check_call(self.pip('.'), cwd=os.path.abspath(self.sourcedirectory))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/c/Git/configsite/debian/configsite/opt/venvs/configsite/bin/python', '/mnt/c/Git/configsite/debian/configsite/opt/venvs/configsite/bin/pip', 'install', '--log=/tmp/tmp6A2iXk', '.']' returned non-zero exit status 1
debian/rules:4: recipe for target 'binary' failed
make: *** [binary] Error 1
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```
I hope I did everything right, my head is spinning from a day's research on packaging Python.

**Comment by nailor** [comment]
Hi, 

is it possible to see example off the setup.py? Or what happens if you run `python setup.py egg_info` in your project? Unfortunately the build eats some error output to tell what actually is broken.

**Comment by Nadav-Ruskin** [comment]
Thanks for the quick reply. Running `python setup.py egg_info` revealed I have made a syntax error in my setup.py. Whoops! Thanks for the pointer.

I'm now encountering an error trying to install the created package:
```
nadav@DESKTOP-4DUIS04:/mnt/c/Git$ sudo dpkg -i configsite_0.1-1_amd64.deb
[sudo] password for nadav:
Selecting previously unselected package configsite.
(Reading database ... 84243 files and directories currently installed.)
Preparing to unpack configsite_0.1-1_amd64.deb ...
dpkg: error processing archive configsite_0.1-1_amd64.deb (--install):
': trigger name contains invalid characteriggers' contains illegal trigger syntax in trigger name '/usr/bin/python2.6
Errors were encountered while processing:
 configsite_0.1-1_amd64.deb
```
I don't have Python 2.6 installed, Ubuntu 18.04 comes with 2.7 and 3.6. I have specifically used the following rules in `/debian/rules`: `dh $@ --with python-virtualenv --python /usr/bin/python3 --builtin-venv`

So as far as I'm concerned, Python 2.6 should not be a requirement, and if it is, shouldn't it be requested by the .deb package?

**Comment by jhermann** [comment]
Remove the CRs you have in your files (dos2unix).

**Comment by Nadav-Ruskin** [comment]
What's a CR?

**Comment by Nadav-Ruskin** [comment]
Alright! Thanks for the help, I can now build a simple `.deb` package. However, I'm still facing some problems:

1) I fixed it now, but I had a problem with my `.triggers` file. The [tutorial](https://dh-virtualenv.readthedocs.io/en/latest/tutorial.html?highlight=triggers) didn't mention it had to end with a newline.

2) Files included in `MANIFEST.in` are missing. Even a simple `include readme.md`.
3) I want to add a postbuild to install the package as a service (it's a small server). The solution found in https://stackoverflow.com/a/36902139/6751061 makes `dpkg-buildpackage -us -uc` fail:
```
nadav@DESKTOP-4DUIS04:/mnt/c/Git/configsite$ dpkg-buildpackage -us -uc -b                                 # Build the *dh-virtualenv* package
dpkg-buildpackage: info: source package configsite
dpkg-buildpackage: info: source version 0.1-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Nadav Ruskin <ruskin.nadav@gmail.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build configsite
 fakeroot debian/rules clean
dh clean --with python-virtualenv --python /usr/bin/python3 --builtin-venv
   dh_testdir -O--python=/usr/bin/python3 -O--builtin-venv
   dh_clean -O--python=/usr/bin/python3 -O--builtin-venv
 debian/rules build
dh build --with python-virtualenv --python /usr/bin/python3 --builtin-venv
   dh_testdir -O--python=/usr/bin/python3 -O--builtin-venv
   dh_update_autotools_config -O--python=/usr/bin/python3 -O--builtin-venv
   dh_auto_configure -O--python=/usr/bin/python3 -O--builtin-venv
 fakeroot debian/rules binary
dh binary --with python-virtualenv --python /usr/bin/python3 --builtin-venv
   dh_testroot -O--python=/usr/bin/python3 -O--builtin-venv
   dh_prep -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installdirs -O--python=/usr/bin/python3 -O--builtin-venv
   dh_install -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installdocs -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installchangelogs -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installexamples -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installman -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installcatalogs -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installcron -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installdebconf -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installemacsen -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installifupdown -O--python=/usr/bin/python3 -O--builtin-venv
   dh_installinfo -O--python=/usr/bin/python3 -O--builtin-venv
   dh_virtualenv -O--python=/usr/bin/python3 -O--builtin-venv
Requirement already satisfied: setuptools in ./debian/configsite/opt/venvs/configsite/lib/python3.6/site-packages (from -r ./requirements.txt (line 1))
Collecting click==6.7 (from -r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting Flask==1.0.2 (from -r ./requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
Collecting gunicorn==19.8.1 (from -r ./requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/55/cb/09fe80bddf30be86abfc06ccb1154f97d6c64bb87111de066a5fc9ccb937/gunicorn-19.8.1-py2.py3-none-any.whl
Collecting itsdangerous==0.24 (from -r ./requirements.txt (line 5))
Collecting Jinja2==2.10 (from -r ./requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting jsonschema==2.6.0 (from -r ./requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting MarkupSafe==1.0 (from -r ./requirements.txt (line 8))
Collecting Werkzeug==0.14.1 (from -r ./requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl
Installing collected packages: click, Werkzeug, itsdangerous, MarkupSafe, Jinja2, Flask, gunicorn, jsonschema
Successfully installed Flask-1.0.2 Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 click-6.7 gunicorn-19.8.1 itsdangerous-0.24 jsonschema-2.6.0
Processing /mnt/c/Git/configsite
Installing collected packages: configsite
  Running setup.py install for configsite ... error
Command "/mnt/c/Git/configsite/debian/configsite/opt/venvs/configsite/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-sp58kper-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vuixw_m1-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/c/Git/configsite/debian/configsite/opt/venvs/configsite/include/site/python3.6/configsite" failed with error code 1 in /tmp/pip-sp58kper-build/
Traceback (most recent call last):
  File "/usr/bin/dh_virtualenv", line 106, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/dh_virtualenv", line 89, in main
    deploy.install_package()
  File "/usr/lib/python2.7/dist-packages/dh_virtualenv/deployment.py", line 236, in install_package
    subprocess.check_call(self.pip('.'), cwd=os.path.abspath(self.sourcedirectory))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/c/Git/configsite/debian/configsite/opt/venvs/configsite/bin/python', '/mnt/c/Git/configsite/debian/configsite/opt/venvs/configsite/bin/pip', 'install', '--log=/tmp/tmpBuXSa1', '.']' returned non-zero exit status 1
debian/rules:4: recipe for target 'binary' failed
make: *** [binary] Error 1
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```


My `setup.py` looks like this:
```
from setuptools import setup, find_packages
from setuptools.command.develop import develop
from setuptools.command.install import install
from subprocess import check_call

class Post_Install_Command(install):
    """Post-installation for installation mode."""
    def run(self):
        check_call("mkdir /test".split())
        install.run(self)



setup(
    name='configsite',
    version='0.1',
    description='A configuration site for DMS demo.',
    package_data={'': ['license.txt']},
    include_package_data=True,
    packages=find_packages(exclude=['ez_setup', 'tests', 'tests.*']),
    install_requires=[],
    cmdclass={
        'install': Post_Install_Command
    }
)
```

The docs mention this:
>Note that if you provide a custom postinst script with your package, then don’t forget to put the #DEBHELPER# marker into it, else the trigger script will be missing.

Is this the proper way to add post install scripts? I can find some information on what a `postinst` is, but not what `#DEBHELPER#` means.

**Comment by jhermann** [comment]
1 - I think there is an issue for that open (or was)
2 - Your source dist won't end up packaged magically, use the related files ⇒ https://www.debian.org/doc/manuals/maint-guide/dother.en.html#docs
3 - See https://github.com/1and1/debianized-sentry/tree/master/debian

**Comment by Nadav-Ruskin** [comment]
1) I see it mentioned in https://github.com/bivald/dh-virtualenv/blob/0b84a3d9824565fc9aa1450b39da66bb60c15dbd/doc/tutorial.rst but it does not appear on master.

2) and 3) I know nothing about making `.deb` packages so pardon my ignorance, but I do see there is a file called "install" [here](https://www.debian.org/doc/manuals/maint-guide/dother.en.html#install). Since what I want to do with my post built is install a daemon, will simply putting a line like `configsite.service /etc/systemd/system` in a file called `install` do the trick?

**Comment by jhermann** [comment]
3 has all the things. just actually look at the files, using the Debian docs for understanding stuff.

**Comment by Nadav-Ruskin** [comment]
Thanks for giving me a place to start. I've finished my package now, but it wasn't easy. dh-virtualenv definitely requires learning the debian packaging process, and is not a simple solution as the articles that made me want to use it made it look like, which direct people with no debian packing background to use it.

I aim to publish a version of my project in github as an example, because I've found `dh` documentation to be very lacking.

Feel free to close this issue, but I'd like to once again mention the edits in https://github.com/bivald/dh-virtualenv/blob/0b84a3d9824565fc9aa1450b39da66bb60c15dbd/doc/tutorial.rst were overridden and should make a comeback.

**Comment by linuxmail** [comment]
hi,

I have also a problem. Everything is working, if I call:

`env PATH="/usr/sbin:/usr/bin:/sbin:/bin" HOME="/nonexistent" dpkg-buildpackage -us -uc -sa -rfakeroot`

but, if the same is called via Jenkins:

```
Also creating executable in /build/foobar-django-0.1.0+0~20190701131727.13~1.gbp117d5e/debian/foobar-django/opt/venvs/foobar-django/bin/python
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /build/foobar-d...1-django/bin/python3 - setuptools pkg_resources pip wheel:
  Collecting setuptools
Exception:
Traceback (most recent call last):
  File "/build/foobar-django-0.1.0+0~20190701131727.13~1.gbp117d5e/debian/foobar-django/opt/venvs/foobar-django/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/build/foobar-django-0.1.0+0~20190701131727.13~1.gbp117d5e/debian/foobar-django/opt/venvs/foobar-django/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/connection.py", line 75, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

...
any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 11, in <module>
    load_entry_point('virtualenv==15.1.0', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 992, in create_environment
    download=download,
    
....
OSError: Command /build/foobar-d...1-django/bin/python3 - setuptools pkg_resources pip wheel failed with error code 2
Traceback (most recent call last):
  File "/usr/bin/dh_virtualenv", line 106, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/dh_virtualenv", line 83, in main
    deploy.create_virtualenv()
  File "/usr/lib/python2.7/dist-packages/dh_virtualenv/deployment.py", line 151, in create_virtualenv
    subprocess.check_call(virtualenv)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--no-site-packages', '--setuptools', '--python', 'python3', 'debian/foobar-django/opt/venvs/foobar-django']' returned non-zero exit status 1
debian/rules:7: recipe for target 'override_dh_virtualenv' failed
make[1]: *** [override_dh_virtualenv] Error 1
make[1]: Leaving directory '/build/foobar-django-0.1.0+0~20190701131727.13~1.gbp117d5e'
debian/rules:5: recipe for target 'binary' failed
```
I've also asked Jenkins to keep the build env and tried the same command, inside the "chroot", what was working too.
At the start from the debugging, I removed also my PROXY / proxy settings from pbuilderrc (Debian Jenkins glue), but than I get an **network unreachable**.

So I have no idea, what is going on and why it work, if I call the cmd manually, but not, if Jenkins call the command.

cu denny

**Comment by jhermann** [comment]
Please do not tack on new problems to existing issues – open your own.
