### ISSUE TITLE
New Release with Python3.11 Support?

### ISSUE THREAD

**Issue by Bastian-Krause** [spotify/dh-virtualenv#355]
#354 added Python3.11 support for dh-virtualenv. Since Debian sid currently ships its python3 package in version [3.11.1-1](https://packages.debian.org/sid/python3), the currently released dh-virtualenv version [1.2.2](https://github.com/spotify/dh-virtualenv/releases/tag/1.2.2) does not work.

I saw that @nailor is also the Debian maintainer for [dh-virtualenv](https://packages.debian.org/sid/dh-virtualenv), it would be best to have a new release and a corresponding Debian package version. I could alternatively send a backport of the patch in #354 as a Debian bug report.

What do you think?

**Comment by ukleinek** [comment]
my 2¢: If I understand correctly, Debian testing is also affected and the problem makes dh-virtualenv useless for all users?!

That would justify a bugreport with severity `grave` against the version in testing which would result in the package being dropped from testing. The next consequence would be that dh-virtualenv is missing in the next release if it's not fixed in a timely manner[1].


[1] https://release.debian.org/bullseye/freeze_policy.html

**Comment by Bastian-Krause** [comment]
> my 2¢: If I understand correctly, Debian testing is also affected and the problem makes dh-virtualenv useless for all users?!

Currently [Debian Bookworm ships Python 3.10](https://wiki.debian.org/Python#Supported_Python_Versions), I guess they will not bump it to 3.11 before the [freeze](https://release.debian.org/bookworm/freeze_policy.html), right? So when Debian Trixie becomes Testing, that will be affected.

**Comment by jluebbe** [comment]
The default Python in Debian bookworm is now 3.11: https://tracker.debian.org/news/1414484/python3-defaults-3111-1-migrated-to-testing/

**Comment by ikus060** [comment]
I'm also affected by this problem. Our build depend on dh-virtualenv and it's fail on Bookworm with the following error:
```
Traceback (most recent call last):
  File "/usr/bin/dh_virtualenv", line 111, in <module>
    sys.exit(main() or 0)
             ^^^^^^
  File "/usr/bin/dh_virtualenv", line 60, in main
    arguments = inspect.getargspec(DebHelper.__init__).args
                ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

Seams related to the fact Bookworm is now using Python3.11 by default.

**Comment by Bastian-Krause** [comment]
For the record: in Debian's dh-virtualenv 1.2.2-1.3 the patch from #354 was cherry-picked as NMU. A dh-virtualenv release including this would still be nice.

**Comment by ikus060** [comment]
@Bastian-Krause 
> dh-virtualenv 1.2.2-1.3 the patch from https://github.com/spotify/dh-virtualenv/pull/354 was cherry-picked as NMU

Does it mean dh-virtualenv should work in Debian Bookworm ?

**Comment by Bastian-Krause** [comment]
> @Bastian-Krause
> 
> > dh-virtualenv 1.2.2-1.3 the patch from #354 was cherry-picked as NMU
> 
> Does it mean dh-virtualenv should work in Debian Bookworm ?

Yes: https://packages.debian.org/bookworm/dh-virtualenv ([changelog](https://metadata.ftp-master.debian.org/changelogs//main/d/dh-virtualenv/dh-virtualenv_1.2.2-1.3_changelog)). Works for me.

**Comment by wferi** [comment]
Please consider cutting a new release, several fixes on the master branch did not make it into distro packages yet (like for example enabling --verbose with --builtin-venv).
